### ISSUE TITLE
Adblock detected on 200

### ISSUE THREAD

**Issue by GRB** [bharathvaj-ganesan/maari.js#3]
Hello,

If the files exist, you get a 200 code, but still you are making the callback. I removed the t() on the 404 and it worked like a charm.

Also you forgot to check the 500 status code.
And also you set the files on current path and not on /js/files, the "normal" place for them.

**Comment by bharathvaj-ganesan** [comment]
_"And also you set the files on current path and not on /js/files, the "normal" place for them."_
Path doesn't matter for the Adblockers. It will check for the extension **.js** and **filename**

_"Also you forgot to check the 500 status code."_
There won't be 500 status code.

_"If the files exist, you get a 200 code, but still you are making the callback. I removed the t() on the 404 and it worked like a charm."_
If you look at the src code you can find that the file is actually not present. I'm tricking the Adblocker as if those files are present. Anyways I will get 404. But the **status** won't be 200 if there is an ablocker

**Comment by bharathvaj-ganesan** [comment]
I'm closing this issue.
